version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: portal-postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "portal"
    restart: always

  spring-boot:
    image: spring-boot
    build:
      context: .
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ${APPLICATION_ROOT_FOLDER}:/usr/src/mymaven
      - ${MAVEN_SETTINGS_FOLDER}:/root/.m2

